In [2]:
import torch
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

## Tensores

Los tensores son una forma de representar datos numericos, pueden ser multidimensionales

In [18]:
#escalares

scalar  = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.shape)
print(scalar.item())

tensor(7)
0
torch.Size([])
7


In [8]:
#vectores
vector = torch.tensor([7, 7])
vector

In [9]:
#matriz

MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
TENSOR = torch.tensor([[[1, 2, 3], 
                        [4, 5, 6], 
                        [7, 8, 9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR_1 = torch.tensor([[[1, 2], [2, 3], [3, 4]]])
TENSOR_1.shape

torch.Size([1, 3, 2])

### Tensores aleatorios

Los tensores aleatorios son importantes porque la manera de aprender de una red neuronal empieza con tensores compuestos de numeros aleatorios y los va ajustando para representar mejor la información

In [22]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7878, 0.7570, 0.0812, 0.1580],
        [0.3258, 0.9054, 0.5252, 0.4182],
        [0.5502, 0.1727, 0.6104, 0.6740]])

In [23]:
#crear un tensor aleatorio con forma similar al tensor de una imagen

random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, colour channels (R, G, B)

### Ceros y unos

In [25]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

### Rango de tensores

In [30]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Para trabajar con diferentes tensores, algunas operaciones requieren que todos los tensores posean el mismo tipo de dato y ciertos shapes

In [32]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0])
print(float_32_tensor)
print(float_32_tensor.dtype)

tensor([3., 6., 9.])
torch.float32


In [35]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Operaciones de tensores
- Suma
- Resta
- Multiplicación (elemento a elemento)
- División
- Multiplicación de matrices

In [36]:
#suma
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [38]:
#multiplicación
print(tensor * 10)
torch.mul(tensor, 10)

tensor([10, 20, 30])


tensor([10, 20, 30])

In [39]:
#multiplicación de matrices
torch.matmul(tensor, tensor)

tensor(14)

In [41]:
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [42]:
tensor_BT = tensor_B.T
tensor_BT

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [43]:
torch.matmul(tensor_A, tensor_BT)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Buscando min, max, mean, etc 

Se necesita que el tipo de dato sea float o complejo

In [4]:
x = torch.rand(10, 10, 10)
print(x)
print(f"min: {torch.min(x)}, max: {torch.max(x)}")
print(f"mean: {torch.mean(x)}")
print(f"sum: {torch.sum(x)}")

tensor([[[3.6018e-01, 2.4264e-01, 6.4117e-01, 7.2993e-01, 8.4728e-01,
          9.4291e-01, 5.9452e-01, 4.3601e-01, 9.7583e-01, 8.4237e-02],
         [3.8716e-01, 7.1829e-01, 9.6179e-01, 8.8213e-01, 7.6020e-03,
          1.3200e-01, 5.1091e-01, 1.7675e-01, 8.9091e-01, 7.1787e-01],
         [3.8871e-01, 7.5153e-01, 6.1966e-01, 5.2148e-01, 3.1831e-01,
          5.2131e-01, 7.1347e-01, 7.7514e-01, 5.7278e-01, 2.6044e-01],
         [5.2058e-01, 5.9357e-01, 8.0003e-01, 5.9735e-01, 8.2489e-01,
          6.7025e-01, 2.2484e-01, 5.4273e-01, 9.2103e-01, 4.1208e-01],
         [5.1388e-01, 8.1049e-01, 4.5766e-01, 4.8093e-01, 9.0398e-01,
          9.0111e-01, 3.6381e-01, 4.0150e-01, 8.0428e-01, 2.9183e-01],
         [3.0702e-01, 4.1226e-01, 2.2660e-01, 1.8326e-02, 2.9149e-01,
          9.6391e-01, 3.8313e-01, 9.9326e-01, 5.5633e-01, 1.0697e-03],
         [3.4181e-01, 3.8527e-01, 7.2154e-01, 9.0535e-01, 7.0501e-01,
          9.2822e-02, 8.3624e-01, 5.8670e-01, 8.9837e-01, 6.5696e-01],
         [9.3

Ahora buscamos la posición que tiene el minimo y el max

In [5]:
x.argmin()

tensor(256)

### Manipulando la forma de un tensor

In [8]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [11]:
#reshape
x_reshaped = x.reshape(3, 3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [12]:
#View
z = x.view(3, 3)
z, x

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [14]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [22]:
#stack
x_stacked = torch.stack([x, x, x], dim = -1)
x_stacked

tensor([[5., 5., 5.],
        [2., 2., 2.],
        [3., 3., 3.],
        [5., 5., 5.],
        [5., 5., 5.],
        [6., 6., 6.],
        [5., 5., 5.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [26]:
#Squeeze
x = torch.rand(1, 2, 4, 1)
x_squeezed = x.squeeze()
print(x, x_squeezed)
print(x.shape, x_squeezed.shape)

tensor([[[[0.9160],
          [0.0383],
          [0.9932],
          [0.6273]],

         [[0.1428],
          [0.7045],
          [0.0374],
          [0.3698]]]]) tensor([[0.9160, 0.0383, 0.9932, 0.6273],
        [0.1428, 0.7045, 0.0374, 0.3698]])
torch.Size([1, 2, 4, 1]) torch.Size([2, 4])


In [27]:
#Unsqueeze

x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
x_squeezed.shape, x_unsqueezed.shape

(torch.Size([2, 4]), torch.Size([1, 2, 4]))

In [28]:
#permute
x_nuevo = torch.rand(size = (224, 224, 3))
x_permuted = x_nuevo.permute(2, 0, 1)
x_permuted.shape

torch.Size([3, 224, 224])

### Indexar

In [29]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [30]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [31]:
x[0][0]

tensor([1, 2, 3])

In [32]:
x[:, 0]

tensor([[1, 2, 3]])

In [33]:
# Index on x to return 9
x[0, -1, -1]

tensor(9)

In [35]:
#index on x to return 3, 6, 9
x[0, :, -1]

tensor([3, 6, 9])

## Pythorch tensors & Numpy arrays

In [37]:
#De array a tensor

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Difieren en el tipo de dato default, el dtype default de los np array es float64 y el de los tensores en float32

In [38]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [39]:
#De tensor a array
tensor = torch.ones(7)
np_tensor = tensor.numpy()

tensor, np_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproductividad (tratando de sacar lo random de lo random)

Lo usamos para que una operación random no sea tan random

In [3]:
random_A = torch.rand(3, 4)
random_B = torch.rand(3, 4)

print(random_A)
print(random_B)
print(random_A == random_B)

tensor([[0.5711, 0.2022, 0.4431, 0.1659],
        [0.6124, 0.0879, 0.6021, 0.9192],
        [0.1030, 0.6882, 0.0713, 0.6941]])
tensor([[0.5115, 0.2240, 0.3794, 0.1300],
        [0.6449, 0.2998, 0.4649, 0.4693],
        [0.9853, 0.6597, 0.1825, 0.5129]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [5]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_D = torch.rand(3, 4)

print(random_C)
print(random_D)
print(random_C == random_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
